permalink: /:categories/:title.html
url: "http://cawa0505.github.io/"
full_name: "Jimmy Yen"
first_name: "Jimmy"
last_name: "Yen"
blog_title: "Junk "
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "zeng"
copyright_year: "2015"
google_analytics_code: ""
aboutme: ""
twitter: "zengtw"
github: "cawa0505"
facebook: "jimmy.yen"
linkined_url: "https://tw.linkedin.com/in/jimmyyen"
